### PR TITLE
Applying suggestions from Julian

### PR DESCRIPTION
**Pull request by martinheidegger**
Applying suggestions from @juliangruber in https://github.com/datproject/dat-desktop/pull/450

### CODE REVIEW

**Comment by aks-** [comment]
@martinheidegger you broke the tests, can you please fix them? I won't be able to make time right now

**Comment by martinheidegger** [comment]
see: https://github.com/aks-/dat-desktop/pull/2#issuecomment-359041057
> The tests are broken but I can't quite understand how (they fail with behavior that I can experience in regular user mode). It would be awesome to get some help tracking them down.

**Comment by aks-** [comment]
@martinheidegger it was working before those 2 commits, so probably something to do with them. I believe it's https://github.com/aks-/dat-desktop/pull/3/commits/ac857059fee85e2c162b9266c6d338173508bd39

**Comment by aks-** [comment]
@martinheidegger it was issue with deps, fixed it. Thanks for making changes to the PR :) You are probably sleeping right now, good night :)

**Pull request merged**
