### PR TITLE
Fixing several problems with the nanocomponent PR

### PR DESCRIPTION
**Pull request by martinheidegger**
Trying to figure out what didn't work with the nanocomponent PR i stumbled over a few issues. I attempted to explain each fix in each commit.

### CODE REVIEW

**Comment by aks-** [comment]
@martinheidegger looks good... you have lint errors, can you please run the test suite.

screen shot 2018-01-19 at 10 08 46 pm

Additionally for some reason it doesn't show name and hexicon on first dat, and still the hexicon is not changing on mouseover

P.S. Thanks for PR :) I will hopefully get some time tomorrow to take a look at it

**Comment by martinheidegger** [comment]
Ah, thank you for point out those errors, I knew i forgot to do something 😅

**Comment by martinheidegger** [comment]
I wasnt able to reproduce your display problem, but I did find some way to improve the hover logic. The tests are broken but I can't quite understand how (they fail with behavior that I can experience in regular user mode). It would be awesome to get some help tracking them down. _(Also I think I should add more tests but its 3am here right now, and family weekend is waiting)_

**Comment by aks-** [comment]
@martinheidegger fixed and merged

**Pull request closed without merging**
